// src/db/data/article-previews.ts — GENERATED by scripts/fetch-article-previews.js
//
// The publisher's OWN title and description for each article the library
// cites, fetched once and committed. Do not edit by hand: run
// `npm run articles:previews` instead, which is idempotent.
//
// These are somebody else's words, shown as a link preview and attributed to
// them by site name and domain, with the link going to their page. That is
// what the card is for -- the article stays a link and the traffic goes to
// them. No image is stored; see the script header for why.
//
// A URL with no entry here is not a failure: its card degrades to the plain
// row, which is what the page did before previews existed.

export interface ArticlePreview {
  /** The publisher's own title, with their site name trimmed off the end. */
  title: string;
  /** The publisher's own description, clamped to 180 characters. */
  description: string;
  /** How the publisher names itself, for the credit line. */
  site: string;
  /** Bare hostname, shown so a reader can see where the link goes. */
  domain: string;
}

export const ARTICLE_PREVIEWS: Record<string, ArticlePreview> = {
  "https://blog.dynamicdiscs.com/2017/09/quick-tip-mental-focus.html": {
    title: "Quick Tip: Mental Focus",
    description: "Hey guys, my name is Robert McCall. I’m the Team Manager for Dynamic Discs, and I’ve been playing disc golf for around 10 years. I’ve pla...",
    site: "blog.dynamicdiscs.com",
    domain: "blog.dynamicdiscs.com",
  },
  "https://blog.infinitediscs.com/best-disc-golf-discs-for-beginners/": {
    title: "Best Disc Golf Discs For Beginners",
    description: "In this blog we talk about which discs are best for beginners to throw, and why. We talk about flight numbers and weight.",
    site: "Infinite Discs Blog",
    domain: "blog.infinitediscs.com",
  },
  "https://blog.infinitediscs.com/disc-golf-exercise-and-injury/": {
    title: "Disc Golf Exercise and Injury",
    description: "This is the survey results from 2019 talking about disc golf exercise and injury, and stretching habits. See how we prepare, and how it helps.",
    site: "Infinite Discs Blog",
    domain: "blog.infinitediscs.com",
  },
  "https://blog.infinitediscs.com/disc-golf-practicing/": {
    title: "Getting Better at Disc Golf Through Practicing",
    description: "This blog talks about methods and benefits of disc golf practicing. Including warming up, driving, putting, and approach shots.",
    site: "Infinite Discs Blog",
    domain: "blog.infinitediscs.com",
  },
  "https://blog.infinitediscs.com/disc-golf-shot-selection-and-ground-play-lower-your-score/": {
    title: "Disc Golf Shot Selection and Ground Play - Lower Your Score!",
    description: "See how disc golf shot selection and ground play are two ways that we can add to our games and lower our scores.",
    site: "Infinite Discs Blog",
    domain: "blog.infinitediscs.com",
  },
  "https://blog.infinitediscs.com/disc-golf-throwing-styles/": {
    title: "Disc Golf Throwing Styles",
    description: "This blog discusses the popular throwing styles, how to practice them and when they are useful. Knowing these shots will improve your game.",
    site: "Infinite Discs Blog",
    domain: "blog.infinitediscs.com",
  },
  "https://blog.infinitediscs.com/disc-golf-tips-on-accuracy/": {
    title: "Disc Golf Tips on Accuracy",
    description: "Disc Golf Accuracy is a crucial component to any player's game. Come read content and watch videos to maximize your learning!",
    site: "Infinite Discs Blog",
    domain: "blog.infinitediscs.com",
  },
  "https://blog.infinitediscs.com/how-to-putt-disc-golf-putting-techniques/": {
    title: "How to Putt: Disc Golf Putting Techniques",
    description: "In this blog you'll learn about some of the most popular putting styles and techniques, and when they are used.",
    site: "Infinite Discs Blog",
    domain: "blog.infinitediscs.com",
  },
  "https://blog.infinitediscs.com/hyzer-vs-anhyzer/": {
    title: "Hyzer vs Anhyzer",
    description: "In this blog we discuss two types of disc golf throws: Hyzer and anhyzer. We'll discuss what they are and when they are used",
    site: "Infinite Discs Blog",
    domain: "blog.infinitediscs.com",
  },
  "https://blog.infinitediscs.com/improve-your-disc-golf-mental-game/": {
    title: "Improve Your Disc Golf Mental Game!",
    description: "Improving your disc golf mental game is a crucial aspect to scoring well when you are on the course. Check out these tips to do just that!",
    site: "Infinite Discs Blog",
    domain: "blog.infinitediscs.com",
  },
  "https://blog.infinitediscs.com/injury-in-disc-golf/": {
    title: "More Injury-Related Survey Results",
    description: "We explore a few more statistics surrounding disc golf and injury. We found a few reasons why people get injured, despite exercising",
    site: "Infinite Discs Blog",
    domain: "blog.infinitediscs.com",
  },
  "https://blog.infinitediscs.com/pro-tips-to-improve-your-disc-golf-forehand/": {
    title: "Pro Tips to Improve Your Disc Golf Forehand!",
    description: "Get pro tips from some of the very best in the game on how to improve your disc golf forehand and improve your overall game as well!",
    site: "Infinite Discs Blog",
    domain: "blog.infinitediscs.com",
  },
  "https://blog.infinitediscs.com/putting-styles-should-you-spin-putt-or-push-putt/": {
    title: "Putting Styles: Should You Spin Putt or Push Putt?",
    description: "In this quick disc golf tutorial, Dave Feldberg discusses the differences between different putting styles. There are advantages and disadvantages to each putting style. Depending…",
    site: "Infinite Discs Blog",
    domain: "blog.infinitediscs.com",
  },
  "https://blog.infinitediscs.com/stretching/": {
    title: "The Value of Stretching for Your Disc Golf Game",
    description: "To start the discussion of the State of Disc Golf survey, we first decided to look at an aspect not often discussed on the golf course. That would be the subject of stretching…",
    site: "Infinite Discs Blog",
    domain: "blog.infinitediscs.com",
  },
  "https://udisc.com/blog/post/3-tips-for-becoming-a-more-consistent-tournament-player": {
    title: "3 Tips For Becoming A More Consistent Tournament Player",
    description: "Consistency is something many hobby disc golfers want in their games. Here are three tips to help you find it.",
    site: "Release Point - The UDisc Blog",
    domain: "udisc.com",
  },
  "https://udisc.com/blog/post/5-great-videos-disc-golf-grip-backhand": {
    title: "Disc Golf Grip (Backhand): 5 Great Videos",
    description: "Get a better grip for your rips. The videos are watchable in the article and we tell you exactly what points are made when for each one.",
    site: "Release Point - The UDisc Blog",
    domain: "udisc.com",
  },
  "https://udisc.com/blog/post/5-great-videos-how-to-forehandsidearm-in-disc-golf": {
    title: "How To Forehand/Sidearm In Disc Golf: 5 Great Videos",
    description: "The best sidearm advice we could find. Videos are watchable in the article and we tell you exactly what points are made when for each one.",
    site: "Release Point - The UDisc Blog",
    domain: "udisc.com",
  },
  "https://udisc.com/blog/post/5-great-videos-how-to-putt-in-disc-golf": {
    title: "How To Putt In Disc Golf: 5 Great Videos",
    description: "Looking to improve on the green? Read this. It includes the videos and a breakdown of their highlights.",
    site: "Release Point - The UDisc Blog",
    domain: "udisc.com",
  },
  "https://udisc.com/blog/post/5-great-videos-how-to-throw-backhand-in-disc-golf": {
    title: "How To Throw Backhand In Disc Golf: 5 Great Videos",
    description: "How to throw a disc golf backhand: 5 videos with drills and advice to help you learn and improve.",
    site: "Release Point - The UDisc Blog",
    domain: "udisc.com",
  },
  "https://udisc.com/blog/post/5-great-videos-how-to-throw-in-disc-golf-beginners": {
    title: "How To Throw In Disc Golf (Beginners): 5 Great Videos",
    description: "Learn to throw and putt a disc golf disc. Videos are watchable in the article and we tell you the exact times you'll find what info.",
    site: "Release Point - The UDisc Blog",
    domain: "udisc.com",
  },
  "https://udisc.com/blog/post/5-great-videos-how-to-throw-upshotsapproaches": {
    title: "How To Throw Upshots/Approaches In Disc Golf: 5 Great Videos",
    description: "Want to shave strokes from your rounds by improving your short game? Read this. It includes the videos and a breakdown of their highlights.",
    site: "Release Point - The UDisc Blog",
    domain: "udisc.com",
  },
  "https://udisc.com/blog/post/a-simple-method-to-calm-disc-golf-tournament-nerves": {
    title: "A Simple Method To Calm Disc Golf Tournament Nerves",
    description: "Learn something that could help make you less nervous at disc golf tournaments and the physiological reasons for why it works.",
    site: "Release Point - The UDisc Blog",
    domain: "udisc.com",
  },
  "https://udisc.com/blog/post/best-disc-golf-discs-for-beginners": {
    title: "The Best Disc Golf Discs For Beginners",
    description: "The best disc golf discs for beginners and how to find them near you or online.",
    site: "Release Point - The UDisc Blog",
    domain: "udisc.com",
  },
  "https://udisc.com/blog/post/disc-golf-disc-numbers-what-they-mean": {
    title: "Disc Golf Disc Numbers: What They Mean (And What They Don't)",
    description: "What do the numbers on a golf disc mean? We explain everything you might want to know.",
    site: "Release Point - The UDisc Blog",
    domain: "udisc.com",
  },
  "https://udisc.com/blog/post/disc-golf-how-to-play-get-discs-find-courses": {
    title: "How To Play Disc Golf For Beginners",
    description: "Everything you need to know about how to play disc golf for the first time: Basic rules, how to buy discs, how to find courses, and more.",
    site: "Release Point - The UDisc Blog",
    domain: "udisc.com",
  },
  "https://udisc.com/blog/post/disc-golf-putting-common-issues-how-to-improve": {
    title: "Disc Golf Putting: Common Issues & How To Improve",
    description: "Tips for refining your putting stroke and mindset on the green based on advice from pros Chris Clemons and Kristin Tattar",
    site: "Release Point - The UDisc Blog",
    domain: "udisc.com",
  },
  "https://udisc.com/blog/post/disc-golf-terms-stability-flight-numbers": {
    title: "Disc Golf Terms: Stability",
    description: "Basic explanation of the terms overstable, understable, and stable as well as flight numbers as they relate to disc golf.",
    site: "Release Point - The UDisc Blog",
    domain: "udisc.com",
  },
  "https://udisc.com/blog/post/disc-golf-tournaments-a-beginners-guide": {
    title: "Disc Golf Tournaments: A Beginner's Guide",
    description: "Your first disc golf tournament: What you need to know before playing it.",
    site: "Release Point - The UDisc Blog",
    domain: "udisc.com",
  },
  "https://udisc.com/blog/post/discs-explained-how-when-to-throw-midranges": {
    title: "Disc Golf Discs Explained: How & When To Throw Midranges",
    description: "What is a midrange in disc golf and how should you throw midranges on the disc golf course?",
    site: "Release Point - The UDisc Blog",
    domain: "udisc.com",
  },
  "https://udisc.com/blog/post/gannon-buhr-background-disc-golf-career-so-far": {
    title: "Gannon Buhr: Background & Disc Golf Career So Far",
    description: "Who is Gannon Buhr? This is your chance to get to know the teenage disc golf superstar a lot better.",
    site: "Release Point - The UDisc Blog",
    domain: "udisc.com",
  },
  "https://udisc.com/blog/post/meaning-origin-of-the-word-hyzer-in-disc-golf": {
    title: "Hyzer In Disc Golf: Meaning, Origin, & How to Throw",
    description: "What a hyzer in disc golf is. Also includes what a hyzer flip is, hyzer vs. anhyzer, and spike hyzer.",
    site: "Release Point - The UDisc Blog",
    domain: "udisc.com",
  },
  "https://udisc.com/blog/post/stay-classy-disc-golfers-rules-of-disc-golf-etiquette": {
    title: "Stay Classy, Disc Golfers: Rules of Disc Golf Etiquette",
    description: "What you should and should not do when playing disc golf.",
    site: "Release Point - The UDisc Blog",
    domain: "udisc.com",
  },
  "https://udisc.com/blog/post/stay-fit-for-disc-golf-prevent-injuries-play-longer": {
    title: "Stay Fit For Disc Golf: Prevent Injuries, Play Longer",
    description: "Ways to prevent disc golf injuries and disc golf-focused workouts to prepare you to perform your best on the disc golf course.",
    site: "Release Point - The UDisc Blog",
    domain: "udisc.com",
  },
  "https://udisc.com/blog/post/what-overstable-stable-understable-mean-in-disc-golf": {
    title: "What Overstable, Stable, & Understable Mean in Disc Golf",
    description: "What does overstable mean in disc golf? What about understable and stable? Why do discs fly differently at all? All your questions answered.",
    site: "Release Point - The UDisc Blog",
    domain: "udisc.com",
  },
  "https://www.discmania.net/blogs/discover/disc-golf-mental-routine": {
    title: "Importance of a Mental Routine in Disc Golf",
    description: "It's all in your head.",
    site: "Discmania Store",
    domain: "discmania.net",
  },
  "https://www.discmania.net/blogs/discover/disc-golf-shot-selection-tips": {
    title: "The Best Shot Selection Secret in Disc Golf",
    description: "Is the MD a better disc go hyzer than the MD3?",
    site: "Discmania Store",
    domain: "discmania.net",
  },
  "https://www.discmania.net/blogs/discover/five-ways-to-improve-your-sidearm": {
    title: "Five Ways to Improve Your Sidearm",
    description: "A good disc golf sidearm throwing technique should have all of the following: control, balance, acceleration, power and follow-through. These are all essential in executing a very…",
    site: "Discmania Store",
    domain: "discmania.net",
  },
  "https://www.discmania.net/blogs/discover/gain-disc-golf-distance-by-slowing-down": {
    title: "Gain Disc Golf Distance By Slowing Down",
    description: "Slower speed discs will lead to better distance. Trust us.",
    site: "Discmania Store",
    domain: "discmania.net",
  },
  "https://www.discmania.net/blogs/discover/improve-your-disc-golf-putting-with-your-mind": {
    title: "Improve Your Disc Golf Putting With Your Mind",
    description: "Physical changes aren't always the solution.",
    site: "Discmania Store",
    domain: "discmania.net",
  },
  "https://www.discmania.net/blogs/discover/top-5-disc-golf-short-game-tips": {
    title: "Top 5 Disc Golf Short Game Tips",
    description: "This article is about how you can improve your short game in disc golf. A majority of players consider practice to be a round of golf at that local course, throwing drives at a…",
    site: "Discmania Store",
    domain: "discmania.net",
  },
  "https://www.dynamicdiscs.com/pages/disc-golf-beginners-guide": {
    title: "Disc Golf Beginner's Guide - Learn How To Play Disc Golf",
    description: "New to disc golf? Learn everything you need to get started in from the types of discs you can throw to tips on developing your disc golf form. Start learning here.",
    site: "Dynamic Discs",
    domain: "dynamicdiscs.com",
  },
  "https://www.dynamicdiscs.com/pages/disc-golf-plastics": {
    title: "Disc Golf Plastics",
    description: "Learn more about the different types of disc golf plastic materials available through Dynamic Discs, Latitude 64, and Westside Discs.",
    site: "Dynamic Discs",
    domain: "dynamicdiscs.com",
  },
  "https://www.innovadiscs.com/disc-golf-discs/in-the-bag-suggested-disc-lineups-for-all-conditions/": {
    title: "Pathfinder Guides: Suggested Disc Lineups for All Conditions",
    description: "Wind, rain, sleet, or snow, nothing will stop you from getting in your Saturday morning round. By changing the discs in your bag depending on the weather or your elevation, you…",
    site: "Innova Disc Golf",
    domain: "innovadiscs.com",
  },
  "https://www.innovadiscs.com/disc-golf-pro-tips/3-steps-to-practice-like-a-pro/": {
    title: "3 Steps to Practice Like a Pro",
    description: "Whether you're learning the basics of disc golf, or you're an experienced looking to improve your game, having a consistent practice routine is a good",
    site: "Innova Disc Golf",
    domain: "innovadiscs.com",
  },
  "https://www.innovadiscs.com/disc-golf-pro-tips/how-field-work-can-make-you-a-better-disc-golfer/": {
    title: "How Field Work Can Make You a Better Disc Golfer",
    description: "Field work is one of the fastest ways to improve at disc golf. It helps you learn your discs and gives you space to test different shot shapes without pressure.",
    site: "Innova Disc Golf",
    domain: "innovadiscs.com",
  },
  "https://www.innovadiscs.com/disc-golf-pro-tips/make-more-putts/": {
    title: "Make More Putts with Dave Dunipace",
    description: "Putting is the key to low scores. Is your focus on point? What shouldn't you focus on? Dave explains in this putting tutorial.",
    site: "Innova Disc Golf",
    domain: "innovadiscs.com",
  },
  "https://www.innovadiscs.com/tips/6-quick-putting-tips/": {
    title: "6 Quick Putting Tips",
    description: "No matter how amazing you are at throwing, if you can’t putt, you can’t score. These are our top tips to help you shave strokes off your round by improving your short game.",
    site: "Innova Disc Golf",
    domain: "innovadiscs.com",
  },
  "https://www.innovadiscs.com/tips/common-throwing-errors-holding-back-your-game/": {
    title: "Common Throwing Errors Holding Back Your Game",
    description: "Most of us reach plateaus in our disc golf game. Your scores haven’t improved in months; your max distance has stagnated and your accuracy isn’t picking up any of the slack. You…",
    site: "Innova Disc Golf",
    domain: "innovadiscs.com",
  },
  "https://www.innovadiscs.com/tips/get-rolling-the-fundamentals-of-throwing-rollers/": {
    title: "Get Rolling: The Fundamentals of Throwing Rollers",
    description: "You are closer to throwing great rollers than you realize. If you have solid form for air shots, then you already understand the mechanics needed to throw rollers. If you know the…",
    site: "Innova Disc Golf",
    domain: "innovadiscs.com",
  },
  "https://www.innovadiscs.com/tips/how-to-throw-backhands-really-far/": {
    title: "How to Throw Backhands... Really Far",
    description: "Adding distance isn’t just about throwing harder. It’s a matter of cleaning up form and making small adjustments that unlock better efficiency. In many cases, learning better form…",
    site: "Innova Disc Golf",
    domain: "innovadiscs.com",
  },
  "https://www.innovadiscs.com/tips/how-to-throw-forehands-accurately-far-and-without-injury/": {
    title: "Level Up Your Forehand",
    description: "The days of being a backhand-only disc golfer are mostly behind us. While a few top players can still get by that way, most courses demand both shots. A reliable forehand gives…",
    site: "Innova Disc Golf",
    domain: "innovadiscs.com",
  },
  "https://www.innovadiscs.com/tips/improve-your-mental-game/": {
    title: "Improve Your Mental Game",
    description: "Good players push through frustrating moments, while the best players use those moments to sharpen their focus for the rest of the round. Good players can execute despite nerves…",
    site: "Innova Disc Golf",
    domain: "innovadiscs.com",
  },
  "https://www.innovadiscs.com/tips/little-known-disc-golf-pro-tips-that-make-a-big-difference/": {
    title: "Little-Known Disc Golf Pro Tips that Make a Big Difference",
    description: "Improving your form isn’t the only way to lower scores. Course strategy, rules awareness, and small decisions can make just as much of a difference. These tips won’t overhaul your…",
    site: "Innova Disc Golf",
    domain: "innovadiscs.com",
  },
  "https://www.innovadiscs.com/tips/master-your-approach-game/": {
    title: "Master Your Approach Game",
    description: "Most players spend plenty of time working on their drives and putts, but the shots in between often get overlooked. A missed 150-foot approach can erase a great drive just as…",
    site: "Innova Disc Golf",
    domain: "innovadiscs.com",
  },
  "https://www.innovadiscs.com/tips/tips-for-playing-disc-golf-in-the-wind/": {
    title: "Tips for Playing Disc Golf in the Wind",
    description: "For disc golfers without much experience in the wind, it can feel like an entirely new game. Your drives seem to have a mind of their own and 10 foot putts become testers. The…",
    site: "Innova Disc Golf",
    domain: "innovadiscs.com",
  },
  "https://www.innovadiscs.com/tips/why-you-should-throw-lightweight-discs/": {
    title: "Why You Should Throw Lightweight Discs",
    description: "Lighter plastic takes less arm speed to get up to cruising velocity, which means you’ll start seeing those satisfying S-curves—flip, glide, and fade—from early on.",
    site: "Innova Disc Golf",
    domain: "innovadiscs.com",
  },
  "https://www.marshallstreetdiscgolf.com/blog/the-ultimate-guide-to-disc-golf-plastics-and-their-impact-on-play": {
    title: "Disc Golf Plastics: An Ultimate Beginner's Guide • Marshall Street Disc Golf",
    description: "Explore the impact of disc golf plastics on flight patterns and play, enhancing your game with the right disc choice.",
    site: "Marshall Street Disc Golf",
    domain: "marshallstreetdiscgolf.com",
  },
};

/**
 * Urls checked and found to publish nothing usable, with the reason. Their
 * cards degrade to the plain row, which is the designed behaviour rather than
 * a gap to be filled by writing a summary of somebody else's article.
 */
export const NO_PREVIEW: Record<string, string> = {
  "https://en.wikipedia.org/wiki/Gannon_Buhr": "no description published",
};

/** The publisher's preview for a url, or undefined when none was fetched. */
export function articlePreview(url: string): ArticlePreview | undefined {
  return ARTICLE_PREVIEWS[url];
}
